# Basic Information 
title: Shijie Gao
position: Ph.D. 
affiliation_univ: University of Virginia
affiliation_univ_link: https://www.virginia.edu/
affiliation_univ_logo: ./assets/img/university-of-virginia-logo-horizontal.svg
affiliation_LL: Link Lab
affiliation_LL_link: https://engineering.virginia.edu/labs-groups/link-lab
affiliation_AMR: AMR Lab
affiliation_AMR_link: https://www.bezzorobotics.com/

email: sjgao@virginia.edu

# Search Engine Optimization (SEO)
# keywords: shijie gao, gao shijie, shijiegao, gaoshijie
canonical: https://shijiegao.github.io
description: Shijie Gao is a PhD at University of Virginia. His research focus on control and motion planning for the autonomous mobile robots.

# The option is used to enable the UVA template.
enable_UVA: true

# The option is used to show the last update time.
enable_last_update: true

# Links 
# If you don't need one of them, you may delete the corresponding line.
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=yS_ZyS0AAAAJ&hl=en
cv_link: assets/files/Resume_ShijieGao.pdf
github_link: 
linkedin: https://www.linkedin.com/in/uva-sjgao
researchgate: https://www.researchgate.net/profile/Shijie-Gao-3
orcid: https://orcid.org/0000-0003-4717-4094
twitter: 

# Images 
avatar: ./assets/img/shijie_gao.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: true

auto_dark_mode: false
# footnote: 
# footnote_link: 

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0
clustrmaps_id: nhAFwlYMdg_NuU55--eMOoOsx_m5NUXhSZ1qqCPBOco

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAM